name: Deploy Hugo site

on:
  push:
    branches:
      - main   # main ブランチに push されたら実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"   # Hugo のバージョン

      - name: Build
        run: hugo --minify         # サイトをビルド

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public    # Hugo の出力先
          publish_branch: gh-pages # デプロイ先ブランチ
